impac:
  protocol: https
  host: api-impac.maestrano.com
  paths:
    mnohub_api: /mnoe/jpi/v1
  pusher:
    key: <%= ENV['impac_pusher_key'] %>
mno:
  protocol: https
  host: api-hub.maestrano.com
  paths:
    root: /api/mnoe/v1
frontend_host:

url_config:
  developer_onboarding_url: <%= ENV['DEVELOPER_ONBOARDING_URL'] %>

product_nids: ["symantec-end-point-protection-cloud-sit","microsoft-azure-bluesky","symantec-email-security-cloud-sit","symantec-web-security-cloud-sit","aws-uat"]

#===============================================
# Feature Flags
#===============================================
dashboard:
  dock:
    enabled: true
  impac:
    enabled: false
  marketplace:
    pricing:
      enabled: true
      currency: USD
  organization_management:
    billing:
      enabled: false
  payment:
    enabled: false
  provisioning:
    enabled: true
  registration:
     enabled: false
api:
  events:
    currency: USD
# Admin Panel Config
admin_panel:
  audit_log:
    enabled: false
  impersonation:
    enabled: true
    consent_required: true
  finance:
    enabled: false
# Allow for a default SMTP server to be set via MnoHub
system:
  organization_requirements:
    - main_address
  smtp:
    address: <%= ENV['SMTP_HOST'] %>
    port: <%= ENV['SMTP_PORT'] %>
<% if ENV['SMTP_DOMAIN']&.present? %>
    domain: <%= ENV['SMTP_DOMAIN'] %>
<% end %>
<% if ENV['SMTP_USERNAME']&.present? %>
    user_name: <%= ENV['SMTP_USERNAME'] %>
<% end %>
<% if ENV['SMTP_PASSWORD']&.present? %>
    password: <%= ENV['SMTP_PASSWORD'] %>
<% end %>
